# Generated by Django 3.0.8 on 2020-08-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminView', '0002_auto_20200809_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hajime',
            name='description',
            field=models.CharField(choices=[('RPL', 'RPL'), ('TKJ', 'TKJ'), ('MM', 'MM')], max_length=100, null=True),
        ),
    ]
